name: zpgs
channels:
  # - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - imageio
  - scikit-image
  - plyfile
  - tqdm
  - pip:
    - -r requirements.txt